/**
 * 커뮤니티 리뷰 목 데이터 시드 스크립트
 * 실행: npx tsx scripts/seed-community-reviews.ts
 */
import { db } from "../server/db";
import { users, communityReviews } from "../shared/schema";
import { count } from "drizzle-orm";

// ─── Lecture Reviews (인강) ───────────────────────────────────────────────────
const lectureReviews = [
  {
    type: "lecture",
    targetName: "현우진의 뉴런 수학 (수능완성편)",
    instructor: "현우진",
    platform: "메가스터디",
    subject: "수학",
    overallRating: 5,
    ratingContent: 5,
    ratingValue: 4,
    ratingManage: 0,
    title: "3등급에서 1등급으로 올려준 강의",
    content: "고2 때 수학이 발목을 잡아서 현우진 선생님 뉴런 수강했습니다. 개념을 단순히 외우는 게 아니라 왜 그렇게 되는지부터 설명해줘서 진짜 이해가 됐어요. 6개월 수강 후 모의고사 3등급 → 1등급 찍었습니다. 강의 길이가 길어서 집중력이 관건이지만, 그만큼 내용이 충실합니다. 수학 기초가 약한 분들한테 특히 추천합니다.",
    prosTagIds: ["명확한_설명", "개념_충실", "문제_다양"],
    consTagIds: ["강의_길이"],
    gradeLevel: "고2",
    gradeBefore: "3등급",
    gradeAfter: "1등급",
    studyDuration: "6개월",
    likes: 47,
    views: 512,
  },
  {
    type: "lecture",
    targetName: "김민정의 수능영어 독해공식",
    instructor: "김민정",
    platform: "이투스",
    subject: "영어",
    overallRating: 5,
    ratingContent: 5,
    ratingValue: 5,
    ratingManage: 0,
    title: "영어 1등급 공식을 알려준 강의",
    content: "영어 지문을 그냥 해석만 하고 있었는데, 이 강의 듣고 나서 구조 분석하는 법을 배웠어요. 특히 빈칸 추론과 주제 파악 유형에서 점수가 많이 올랐습니다. 선생님이 오답 선지를 왜 틀렸는지까지 꼼꼼하게 설명해줘서 실력이 진짜 늘어요. 고3 초반에 시작하면 좋을 것 같습니다.",
    prosTagIds: ["명확한_설명", "오답_분석", "실전_문제"],
    consTagIds: [],
    gradeLevel: "고3",
    gradeBefore: "3등급",
    gradeAfter: "1등급",
    studyDuration: "4개월",
    likes: 38,
    views: 430,
  },
  {
    type: "lecture",
    targetName: "최규 국어 독서의 원리",
    instructor: "최규",
    platform: "대성마이맥",
    subject: "국어",
    overallRating: 4,
    ratingContent: 5,
    ratingValue: 3,
    ratingManage: 0,
    title: "독서 점수 올리고 싶다면 추천",
    content: "수능 국어 독서 영역이 약해서 수강했습니다. 지문을 읽는 속도가 너무 느렸는데, 선생님이 알려주신 독서법대로 연습하니까 속도도 빨라지고 정확도도 올라갔어요. 다만 가격이 좀 비싼 편이라 가성비는 보통 정도입니다. 강의 자체 퀄리티는 굉장히 높습니다.",
    prosTagIds: ["독해_전략", "개념_충실"],
    consTagIds: ["가격_높음"],
    gradeLevel: "고3",
    gradeBefore: "4등급",
    gradeAfter: "2등급",
    studyDuration: "3개월",
    likes: 29,
    views: 338,
  },
  {
    type: "lecture",
    targetName: "이지영의 생명과학1 개념완성",
    instructor: "이지영",
    platform: "EBSi",
    subject: "생명과학",
    overallRating: 5,
    ratingContent: 5,
    ratingValue: 5,
    ratingManage: 0,
    title: "EBS 강의인데 이 정도면 충분해요",
    content: "무료 강의인데 내용이 진짜 알찹니다. 생명과학1 개념을 그림과 함께 정말 쉽게 설명해줘서 처음 배우는 학생들도 이해하기 쉬워요. EBSi라 수능특강이랑 연계가 잘 돼서 따로 다른 강의 필요 없을 정도입니다. 고2 때 들으면 고3에 훨씬 수월합니다.",
    prosTagIds: ["무료", "개념_충실", "수능_연계"],
    consTagIds: ["강의_속도"],
    gradeLevel: "고2",
    gradeBefore: "4등급",
    gradeAfter: "2등급",
    studyDuration: "5개월",
    likes: 55,
    views: 601,
  },
  {
    type: "lecture",
    targetName: "강민철의 수능국어 문학개념",
    instructor: "강민철",
    platform: "메가스터디",
    subject: "국어",
    overallRating: 5,
    ratingContent: 5,
    ratingValue: 4,
    ratingManage: 0,
    title: "문학 개념 완벽 정리, 국어 1등급 공부법",
    content: "고3 올라가기 전에 문학 기초를 다지려고 들었어요. 시, 소설, 수필 각 갈래별로 분석 방법을 체계적으로 가르쳐줘서 지문을 보는 눈이 생겼습니다. 선생님 특유의 유머로 지루하지 않게 강의해줘서 집중하기 좋아요. 국어 2~4등급에서 상향 목표하는 분들께 강추합니다.",
    prosTagIds: ["명확한_설명", "유머", "체계적"],
    consTagIds: [],
    gradeLevel: "고2",
    gradeBefore: "3등급",
    gradeAfter: "1등급",
    studyDuration: "4개월",
    likes: 62,
    views: 710,
  },
  {
    type: "lecture",
    targetName: "정우성의 화학1 완전정복",
    instructor: "정우성",
    platform: "시대인재 온라인",
    subject: "화학",
    overallRating: 4,
    ratingContent: 4,
    ratingValue: 4,
    ratingManage: 0,
    title: "화학 처음부터 다시 잡아준 강의",
    content: "화학1이 너무 어려워서 포기하려다가 이 강의 보고 마음 바뀌었어요. 개념 설명이 깔끔하고 공식 유도 과정도 보여줘서 외우는 게 아니라 이해하는 느낌입니다. 단, 심화 내용은 다른 강의랑 병행해야 할 것 같아요. 기초~중급 학생들에게 추천합니다.",
    prosTagIds: ["개념_충실", "친절한_설명"],
    consTagIds: ["심화_부족"],
    gradeLevel: "고3",
    gradeBefore: "5등급",
    gradeAfter: "3등급",
    studyDuration: "3개월",
    likes: 21,
    views: 287,
  },
  {
    type: "lecture",
    targetName: "박봄의 수능영어 어법어휘",
    instructor: "박봄",
    platform: "이투스",
    subject: "영어",
    overallRating: 4,
    ratingContent: 4,
    ratingValue: 5,
    ratingManage: 0,
    title: "어법 문제는 이 강의 하나로 끝",
    content: "수능 영어 어법 파트에서 늘 실수가 잦았는데 이 강의 듣고 나서 어법 문제 거의 다 맞히고 있어요. 자주 출제되는 어법 포인트를 패턴별로 정리해줘서 빠르게 학습할 수 있습니다. 어휘 파트도 챕터별로 나눠서 체계적으로 공부할 수 있어요. 가격 대비 내용이 알찹니다.",
    prosTagIds: ["패턴_정리", "가성비"],
    consTagIds: ["독해_미포함"],
    gradeLevel: "고2",
    gradeBefore: "3등급",
    gradeAfter: "2등급",
    studyDuration: "2개월",
    likes: 34,
    views: 399,
  },
  {
    type: "lecture",
    targetName: "한상훈의 지구과학1 기출분석",
    instructor: "한상훈",
    platform: "대성마이맥",
    subject: "지구과학",
    overallRating: 5,
    ratingContent: 5,
    ratingValue: 4,
    ratingManage: 0,
    title: "기출 분석의 끝판왕, 지구과학 1등급 달성",
    content: "지구과학1 기출을 혼자 풀다가 해설이 이해 안 돼서 수강했어요. 선생님이 기출 문제 하나하나를 정말 꼼꼼하게 분석해주고 출제 의도까지 설명해줘서 다음에 유사 문제가 나오면 바로 풀 수 있게 됩니다. 지구과학으로 수능 보는 분들 필수 강의라고 생각해요.",
    prosTagIds: ["기출_분석", "명확한_설명"],
    consTagIds: ["강의_수_많음"],
    gradeLevel: "고3",
    gradeBefore: "3등급",
    gradeAfter: "1등급",
    studyDuration: "5개월",
    likes: 43,
    views: 488,
  },
  {
    type: "lecture",
    targetName: "김동욱의 수학2 미적분 집중",
    instructor: "김동욱",
    platform: "스카이에듀",
    subject: "수학",
    overallRating: 3,
    ratingContent: 4,
    ratingValue: 3,
    ratingManage: 0,
    title: "미적분은 좋은데 전체적으로 평범한 수준",
    content: "미적분 파트는 설명이 정말 좋았어요. 극한·연속·미분·적분 흐름이 자연스럽게 이어져서 이해하기 쉬웠습니다. 다만 수학2 다른 파트는 좀 아쉬운 부분이 있고, 가격 대비 메가스터디 강의들이랑 비교하면 조금 떨어지는 것 같아요. 미적분만 집중적으로 공부하려는 분에게 추천합니다.",
    prosTagIds: ["미적분_강점", "친절한_설명"],
    consTagIds: ["가성비_보통", "내용_불균형"],
    gradeLevel: "고3",
    gradeBefore: "4등급",
    gradeAfter: "3등급",
    studyDuration: "2개월",
    likes: 12,
    views: 189,
  },
  {
    type: "lecture",
    targetName: "오르비 박지훈의 국어 화법작문언어",
    instructor: "박지훈",
    platform: "오르비스옵티무스",
    subject: "국어",
    overallRating: 4,
    ratingContent: 4,
    ratingValue: 4,
    ratingManage: 0,
    title: "화법·작문·언어 이 강의로 거의 해결",
    content: "수능 국어에서 항상 화법작문언어 파트에서 실수가 있었는데, 이 강의 들으면서 유형별 접근법을 익혔어요. 특히 언어(문법) 파트를 쉽게 정리해줘서 좋았습니다. 강의 길이도 적당하고 속도감 있게 진행돼서 지루하지 않았어요.",
    prosTagIds: ["유형_정리", "적절한_속도"],
    consTagIds: [],
    gradeLevel: "고3",
    gradeBefore: "3등급",
    gradeAfter: "2등급",
    studyDuration: "2개월",
    likes: 27,
    views: 303,
  },
  {
    type: "lecture",
    targetName: "노베이스도 되는 한국사 완성",
    instructor: "최태성",
    platform: "EBSi",
    subject: "한국사",
    overallRating: 5,
    ratingContent: 5,
    ratingValue: 5,
    ratingManage: 0,
    title: "별★별 한국사, 진짜 최고입니다",
    content: "한국사 수능 최저 맞춰야 해서 단기간에 공부했는데, 최태성 선생님 강의가 정말 최고예요. 스토리텔링으로 역사를 설명해줘서 암기가 아니라 이해가 됩니다. 무료 강의인데 유료 강의보다 퀄리티가 높아요. 한국사 1등급 목표라면 이 강의 하나로 충분합니다.",
    prosTagIds: ["무료", "스토리텔링", "이해_중심"],
    consTagIds: [],
    gradeLevel: "고3",
    gradeBefore: "4등급",
    gradeAfter: "1등급",
    studyDuration: "2개월",
    likes: 89,
    views: 1023,
  },
  {
    type: "lecture",
    targetName: "윤혜정의 나비효과 국어 입문",
    instructor: "윤혜정",
    platform: "EBSi",
    subject: "국어",
    overallRating: 5,
    ratingContent: 5,
    ratingValue: 5,
    ratingManage: 0,
    title: "국어 기초 없으면 이거부터 시작하세요",
    content: "국어를 어떻게 공부해야 할지 몰랐는데, 윤혜정 선생님 나비효과 강의가 방향을 잡아줬어요. 문학·비문학 전 영역을 체계적으로 정리해주고, 수능 국어가 무엇을 물어보는지 근본적으로 이해시켜줍니다. 고1, 고2 학생들한테 강추합니다. 무료라서 더욱 감사한 강의예요.",
    prosTagIds: ["무료", "체계적", "기초_강점"],
    consTagIds: [],
    gradeLevel: "고1",
    gradeBefore: "5등급",
    gradeAfter: "3등급",
    studyDuration: "3개월",
    likes: 76,
    views: 852,
  },
  {
    type: "lecture",
    targetName: "장동준의 수학1 수열완전정복",
    instructor: "장동준",
    platform: "메가스터디",
    subject: "수학",
    overallRating: 4,
    ratingContent: 4,
    ratingValue: 4,
    ratingManage: 0,
    title: "수열이 약했는데 이제 자신 있어요",
    content: "수열 단원이 늘 발목을 잡았는데, 이 강의 듣고 나서 수열 문제를 자신 있게 풀게 됐어요. 등차·등비수열부터 수학적 귀납법까지 단계별로 차근차근 가르쳐줘서 좋아요. 문제 유형도 다양하게 다뤄줘서 실전 감각도 키울 수 있습니다.",
    prosTagIds: ["단계별_학습", "문제_다양"],
    consTagIds: ["다른_단원_미포함"],
    gradeLevel: "고2",
    gradeBefore: "4등급",
    gradeAfter: "2등급",
    studyDuration: "1개월",
    likes: 19,
    views: 241,
  },
  {
    type: "lecture",
    targetName: "조정식의 영어 독해공식 Season2",
    instructor: "조정식",
    platform: "시대인재 온라인",
    subject: "영어",
    overallRating: 5,
    ratingContent: 5,
    ratingValue: 4,
    ratingManage: 0,
    title: "독해 속도랑 정확도 둘 다 올려준 강의",
    content: "고3 모의고사에서 시간이 항상 부족했는데, 조정식 선생님이 알려준 독해 공식 적용하니까 시간 단축됐어요. 지문 구조를 파악하는 훈련을 반복하게 해줘서 처음 보는 지문도 빠르게 이해할 수 있게 됩니다. 어렵고 긴 지문이 많이 나오는 수능 대비에 딱입니다.",
    prosTagIds: ["속도_향상", "실전_적용"],
    consTagIds: ["가격_높음"],
    gradeLevel: "고3",
    gradeBefore: "3등급",
    gradeAfter: "1등급",
    studyDuration: "4개월",
    likes: 51,
    views: 567,
  },
  {
    type: "lecture",
    targetName: "이다지의 세계사 완전정복",
    instructor: "이다지",
    platform: "메가스터디",
    subject: "세계사",
    overallRating: 5,
    ratingContent: 5,
    ratingValue: 5,
    ratingManage: 0,
    title: "세계사를 이렇게 재밌게 배울 수 있다니",
    content: "세계사 선택했는데 방대한 내용에 막막했어요. 이다지 선생님이 핵심만 짚어서 스토리로 연결해주니까 자연스럽게 외워집니다. 강의 중간중간 재미있는 설명으로 집중력이 떨어지지 않아요. 사탐 세계사 선택한 학생이라면 1순위 강의입니다.",
    prosTagIds: ["스토리텔링", "흥미로운_설명", "가성비"],
    consTagIds: [],
    gradeLevel: "고3",
    gradeBefore: "5등급",
    gradeAfter: "2등급",
    studyDuration: "4개월",
    likes: 66,
    views: 742,
  },
  {
    type: "lecture",
    targetName: "홍기빈의 물리학1 기출완성",
    instructor: "홍기빈",
    platform: "이투스",
    subject: "물리학",
    overallRating: 4,
    ratingContent: 5,
    ratingValue: 3,
    ratingManage: 0,
    title: "물리1 기출 마스터, 하지만 가격이 부담",
    content: "물리학1 기출 문제를 혼자 분석하기 힘들어서 수강했어요. 선생님이 기출 풀이 과정을 매우 꼼꼼하게 설명해줘서 물리1 원리를 다시 한번 정립할 수 있었습니다. 내용은 정말 좋은데 가격이 다른 강의에 비해 좀 비싼 편입니다. 물리1로 고점 노리는 분들한테 추천해요.",
    prosTagIds: ["기출_분석", "꼼꼼한_설명"],
    consTagIds: ["가격_높음"],
    gradeLevel: "N수생",
    gradeBefore: "3등급",
    gradeAfter: "1등급",
    studyDuration: "5개월",
    likes: 33,
    views: 377,
  },
  {
    type: "lecture",
    targetName: "배기범의 미적분 완성",
    instructor: "배기범",
    platform: "EBSi",
    subject: "수학",
    overallRating: 4,
    ratingContent: 4,
    ratingValue: 5,
    ratingManage: 0,
    title: "무료인데 미적분 개념 완벽하게 다져줌",
    content: "EBSi 무료 강의 중에 배기범 선생님 미적분 강의가 제일 좋았어요. 개념을 빠짐없이 다루면서도 이해하기 쉽게 설명해줍니다. 무료라서 부담 없이 들을 수 있고, 기본기를 다지는 데 충분해요. 고2 학생이라면 선행으로 들어도 좋을 것 같아요.",
    prosTagIds: ["무료", "개념_충실", "친절한_설명"],
    consTagIds: ["심화_부족"],
    gradeLevel: "고2",
    gradeBefore: "4등급",
    gradeAfter: "3등급",
    studyDuration: "3개월",
    likes: 40,
    views: 455,
  },
  {
    type: "lecture",
    targetName: "손주은의 경제 개념완성",
    instructor: "손주은",
    platform: "대성마이맥",
    subject: "경제",
    overallRating: 4,
    ratingContent: 4,
    ratingValue: 4,
    ratingManage: 0,
    title: "경제 선택했다면 이 강의면 충분해요",
    content: "경제 개념이 추상적이어서 이해하기 힘들었는데, 실생활 예시로 설명해줘서 바로 이해됐어요. 그래프 읽는 법이나 경제 지표 해석 방법도 친절하게 가르쳐줍니다. 다만 심화 문제 대비는 별도 문제집과 함께 공부하는 걸 추천드려요.",
    prosTagIds: ["실생활_예시", "친절한_설명"],
    consTagIds: ["심화_부족"],
    gradeLevel: "고3",
    gradeBefore: "4등급",
    gradeAfter: "2등급",
    studyDuration: "3개월",
    likes: 17,
    views: 213,
  },
  {
    type: "lecture",
    targetName: "김창묵의 사회·문화 기출특강",
    instructor: "김창묵",
    platform: "스카이에듀",
    subject: "사회문화",
    overallRating: 5,
    ratingContent: 5,
    ratingValue: 4,
    ratingManage: 0,
    title: "사회문화 표 분석, 드디어 완벽히 이해했어요",
    content: "사회문화에서 표 분석 문제에서 늘 틀렸는데, 이 강의 들으니까 해결됐어요. 선생님이 기출에서 자주 나오는 표 유형을 분류해서 각각 분석하는 법을 가르쳐줍니다. 개념 암기보다 적용 연습에 집중하는 강의라 실전에 강해집니다.",
    prosTagIds: ["표_분석", "실전_강점", "기출_중심"],
    consTagIds: [],
    gradeLevel: "고3",
    gradeBefore: "3등급",
    gradeAfter: "1등급",
    studyDuration: "3개월",
    likes: 36,
    views: 411,
  },
  {
    type: "lecture",
    targetName: "뇨뇨의 수능 영어 빈칸추론",
    instructor: "조수경",
    platform: "이투스",
    subject: "영어",
    overallRating: 3,
    ratingContent: 3,
    ratingValue: 4,
    ratingManage: 0,
    title: "빈칸 유형에만 집중해서 효율은 좋음",
    content: "빈칸 추론이 너무 어려워서 찾아 들었어요. 빈칸 문제만 집중적으로 다루는 강의라 해당 유형 점수는 올랐습니다. 하지만 다른 유형은 다루지 않아서 영어 전반적인 공부와 병행해야 해요. 빈칸 유형만 집중 보완하려는 분들께 효율적입니다.",
    prosTagIds: ["유형_집중", "가성비"],
    consTagIds: ["다른_유형_미포함"],
    gradeLevel: "고3",
    gradeBefore: "3등급",
    gradeAfter: "2등급",
    studyDuration: "1개월",
    likes: 14,
    views: 178,
  },
  {
    type: "lecture",
    targetName: "이원준의 수능 한국지리 완성",
    instructor: "이원준",
    platform: "메가스터디",
    subject: "한국지리",
    overallRating: 4,
    ratingContent: 4,
    ratingValue: 4,
    ratingManage: 0,
    title: "지리 개념 정리가 깔끔해요",
    content: "한국지리를 선택과목으로 골랐는데 지리는 어디서부터 공부해야 할지 막막했어요. 이 강의는 지역별 특징부터 지형·기후까지 체계적으로 정리해줍니다. 지도 보는 연습도 병행하면 더욱 효과가 좋아요. 한국지리 기초부터 다지고 싶은 분들께 추천합니다.",
    prosTagIds: ["체계적", "지도_활용"],
    consTagIds: ["기출_분석_부족"],
    gradeLevel: "고2",
    gradeBefore: "5등급",
    gradeAfter: "3등급",
    studyDuration: "3개월",
    likes: 22,
    views: 267,
  },
  {
    type: "lecture",
    targetName: "김봉소의 수능 수학 확률과통계",
    instructor: "김봉소",
    platform: "대성마이맥",
    subject: "수학",
    overallRating: 4,
    ratingContent: 4,
    ratingValue: 5,
    ratingManage: 0,
    title: "확통 개념 빠르게 잡고 싶으면 이거",
    content: "확률과 통계는 단기간에 끝낼 수 있다고 들었는데, 이 강의가 딱이에요. 핵심 개념과 자주 나오는 유형을 빠르게 다뤄줘서 시간 대비 효율이 좋습니다. 가격도 저렴해서 부담이 없고요. 확통 선택한 수험생들한테 강추드립니다.",
    prosTagIds: ["효율적", "가성비", "핵심_집중"],
    consTagIds: ["심화_부족"],
    gradeLevel: "고3",
    gradeBefore: "3등급",
    gradeAfter: "2등급",
    studyDuration: "2개월",
    likes: 28,
    views: 324,
  },
  {
    type: "lecture",
    targetName: "설민석의 근현대사 특강",
    instructor: "설민석",
    platform: "EBSi",
    subject: "한국사",
    overallRating: 5,
    ratingContent: 5,
    ratingValue: 5,
    ratingManage: 0,
    title: "근현대사 30일 만에 완성",
    content: "한국사에서 근현대사 파트가 제일 약했는데, 이 특강 들으면서 한 달 만에 정리됐어요. 선생님이 시대별 흐름을 명확하게 잡아줘서 사건들이 자연스럽게 연결됩니다. 무료 강의라 부담도 없어요. 수능 한국사 완성하고 싶은 분들 꼭 들어보세요.",
    prosTagIds: ["무료", "흐름_파악", "이해_중심"],
    consTagIds: [],
    gradeLevel: "고3",
    gradeBefore: "4등급",
    gradeAfter: "1등급",
    studyDuration: "1개월",
    likes: 72,
    views: 834,
  },
  {
    type: "lecture",
    targetName: "김상훈의 수능 수학 기하",
    instructor: "김상훈",
    platform: "이투스",
    subject: "수학",
    overallRating: 3,
    ratingContent: 3,
    ratingValue: 3,
    ratingManage: 0,
    title: "기하는 원래 어려운데, 이 강의는 적당한 수준",
    content: "기하를 선택했는데 워낙 내용이 어렵다 보니 강의 내용도 따라가기 쉽지 않아요. 설명이 친절하긴 한데 기하 자체가 비직관적이라 한 번에 이해가 안 되는 부분도 있습니다. 반복해서 들으면 도움은 되는데, 기하를 처음 접하는 학생이라면 좀 힘들 수 있어요.",
    prosTagIds: ["친절한_설명"],
    consTagIds: ["난이도_높음", "반복_필요"],
    gradeLevel: "고3",
    gradeBefore: "4등급",
    gradeAfter: "3등급",
    studyDuration: "3개월",
    likes: 8,
    views: 132,
  },
  {
    type: "lecture",
    targetName: "노범석의 통합과학 개념완성",
    instructor: "노범석",
    platform: "EBSi",
    subject: "통합과학",
    overallRating: 4,
    ratingContent: 4,
    ratingValue: 5,
    ratingManage: 0,
    title: "고1 통합과학 이 강의로 완벽히 대비했어요",
    content: "고1 통합과학 내신과 학력평가 대비로 수강했어요. 물리·화학·생물·지구과학을 통합해서 설명해주는 방식이 교과서보다 훨씬 이해가 잘 됩니다. 무료 강의라서 부담 없이 시작할 수 있고, 고1 과학 기본기를 다지는 데 충분해요.",
    prosTagIds: ["무료", "통합적_접근", "고1_적합"],
    consTagIds: ["깊이_부족"],
    gradeLevel: "고1",
    gradeBefore: "3등급",
    gradeAfter: "2등급",
    studyDuration: "4개월",
    likes: 45,
    views: 521,
  },
];

// ─── Workbook Reviews (문제집) ────────────────────────────────────────────────
const workbookReviews = [
  {
    type: "workbook",
    targetName: "수능완성 수학영역 (EBS)",
    publisher: "EBS",
    subject: "수학",
    overallRating: 5,
    ratingContent: 5,
    ratingValue: 5,
    ratingManage: 0,
    title: "수능 수학 마무리는 수능완성으로",
    content: "EBS 수능완성 수학은 수능 직전에 꼭 풀어야 하는 문제집이에요. 수능 연계율이 높아서 실제 수능에서 유사 문제가 많이 나옵니다. 난이도가 좀 있어서 기본기가 어느 정도 갖춰진 후에 푸는 게 좋아요. 고3 여름방학 이후에 시작하는 걸 추천합니다.",
    prosTagIds: ["수능_연계", "실전_대비"],
    consTagIds: ["난이도_높음"],
    gradeLevel: "고3",
    gradeBefore: "2등급",
    gradeAfter: "1등급",
    studyDuration: "3개월",
    likes: 58,
    views: 643,
  },
  {
    type: "workbook",
    targetName: "마더텅 수능기출문제집 영어독해",
    publisher: "마더텅",
    subject: "영어",
    overallRating: 5,
    ratingContent: 5,
    ratingValue: 5,
    ratingManage: 0,
    title: "기출 총정리의 끝판왕, 영어독해 필수템",
    content: "마더텅 영어독해 기출문제집은 역대 수능·모의고사 기출을 유형별로 정리해줘서 공부하기 정말 편해요. 해설도 꼼꼼하게 돼 있고, 직독직해부터 구문 분석까지 자세히 나와 있어요. 가격 대비 문제 수가 엄청나서 가성비도 최고입니다. 영어 독해 기본서로 강력 추천합니다.",
    prosTagIds: ["기출_총정리", "가성비", "꼼꼼한_해설"],
    consTagIds: ["무거운_두께"],
    gradeLevel: "고2",
    gradeBefore: "3등급",
    gradeAfter: "1등급",
    studyDuration: "4개월",
    likes: 82,
    views: 921,
  },
  {
    type: "workbook",
    targetName: "수능특강 국어영역 독서 (EBS)",
    publisher: "EBS",
    subject: "국어",
    overallRating: 4,
    ratingContent: 4,
    ratingValue: 5,
    ratingManage: 0,
    title: "수능 연계 필수, 반드시 풀어야 하는 교재",
    content: "수능 국어에서 EBS 연계가 이루어지기 때문에 수능특강은 필수로 봐야 합니다. 독서 지문의 수준이 상당히 높아서 처음에는 어렵지만, 반복해서 읽으면 수능 지문 난이도에 적응하게 됩니다. 지문을 그냥 읽는 게 아니라 강의랑 병행해서 분석하며 공부하는 걸 추천해요.",
    prosTagIds: ["수능_연계", "지문_수준_높음"],
    consTagIds: ["어려움", "단독_학습_어려움"],
    gradeLevel: "고3",
    gradeBefore: "3등급",
    gradeAfter: "2등급",
    studyDuration: "4개월",
    likes: 47,
    views: 533,
  },
  {
    type: "workbook",
    targetName: "자이스토리 수학1+2 기출문제집",
    publisher: "수경출판사",
    subject: "수학",
    overallRating: 4,
    ratingContent: 4,
    ratingValue: 4,
    ratingManage: 0,
    title: "기출 반복 학습에 최적화된 문제집",
    content: "자이스토리는 기출을 단원별로 잘 정리해서 특정 단원 집중 학습에 좋아요. 해설이 자세하게 되어 있고, 오답 노트 공간도 있어서 활용하기 좋습니다. 중위권 학생들이 기본기를 다지면서 기출 감각을 익히기에 딱 적합한 문제집이에요.",
    prosTagIds: ["단원별_정리", "꼼꼼한_해설", "오답_노트"],
    consTagIds: ["심화_부족"],
    gradeLevel: "고2",
    gradeBefore: "4등급",
    gradeAfter: "3등급",
    studyDuration: "3개월",
    likes: 35,
    views: 402,
  },
  {
    type: "workbook",
    targetName: "씨뮬 10년간 수능 영어 기출",
    publisher: "에듀기프트",
    subject: "영어",
    overallRating: 4,
    ratingContent: 4,
    ratingValue: 4,
    ratingManage: 0,
    title: "10년치 기출을 한 권으로, 가성비 굿",
    content: "씨뮬 기출문제집은 연도별로 정리가 잘 되어 있어서 연도별 경향 변화를 파악하기 좋아요. 10년치를 한 권에 담아서 문제 수가 엄청 많고, 가격 대비 분량이 좋습니다. 다만 해설이 좀 부실한 편이라 해설 위주로 공부하려면 다른 교재와 병행하는 게 좋아요.",
    prosTagIds: ["기출_총정리", "가성비"],
    consTagIds: ["해설_부실"],
    gradeLevel: "고3",
    gradeBefore: "3등급",
    gradeAfter: "2등급",
    studyDuration: "4개월",
    likes: 24,
    views: 280,
  },
  {
    type: "workbook",
    targetName: "개념원리 수학1 (고등)",
    publisher: "개념원리",
    subject: "수학",
    overallRating: 5,
    ratingContent: 5,
    ratingValue: 4,
    ratingManage: 0,
    title: "수학 기초부터 잡고 싶다면 개념원리",
    content: "수학 개념을 처음 배울 때 제일 좋은 교재라고 생각해요. 개념 설명이 쉽고 단계적이어서 수학이 약한 학생도 따라갈 수 있습니다. 예제와 연습문제가 잘 구성되어 있어서 개념을 익히면서 바로 적용해볼 수 있어요. 수1 처음 공부하는 고1 학생들한테 강추합니다.",
    prosTagIds: ["개념_충실", "단계적_학습", "기초_적합"],
    consTagIds: ["심화_부족"],
    gradeLevel: "고1",
    gradeBefore: "4등급",
    gradeAfter: "2등급",
    studyDuration: "4개월",
    likes: 63,
    views: 712,
  },
  {
    type: "workbook",
    targetName: "수능완성 국어영역 문학 (EBS)",
    publisher: "EBS",
    subject: "국어",
    overallRating: 4,
    ratingContent: 4,
    ratingValue: 5,
    ratingManage: 0,
    title: "문학 연계 대비는 수능완성으로",
    content: "수능완성 문학 파트에는 EBS 연계 작품이 실려 있어서 수능 직전에 반드시 봐야 해요. 작품 해설이 꼼꼼하게 돼 있고, 연계 포인트도 표시되어 있어서 효율적으로 공부할 수 있습니다. 가격도 적당하고, 공식 교재라 믿음이 가요.",
    prosTagIds: ["수능_연계", "가성비", "꼼꼼한_해설"],
    consTagIds: ["얇은_두께"],
    gradeLevel: "고3",
    gradeBefore: "3등급",
    gradeAfter: "2등급",
    studyDuration: "2개월",
    likes: 41,
    views: 473,
  },
  {
    type: "workbook",
    targetName: "RPM 수학 미적분 (개념+유형)",
    publisher: "비상교육",
    subject: "수학",
    overallRating: 4,
    ratingContent: 4,
    ratingValue: 4,
    ratingManage: 0,
    title: "미적분 개념과 유형 함께 잡기",
    content: "RPM은 개념 정리 후 유형별 문제 연습까지 한 권으로 할 수 있어요. 미적분 전 범위를 다루고, 난이도가 기본~중상 수준이라 수능 준비 초기에 활용하기 좋습니다. 문제 수도 적당하고 해설도 충실해요. 개념원리 이후 단계로 풀면 딱 좋은 교재입니다.",
    prosTagIds: ["개념_유형_함께", "충실한_해설"],
    consTagIds: ["최고난도_부족"],
    gradeLevel: "고2",
    gradeBefore: "3등급",
    gradeAfter: "2등급",
    studyDuration: "3개월",
    likes: 29,
    views: 331,
  },
  {
    type: "workbook",
    targetName: "마더텅 수능기출 국어 문학",
    publisher: "마더텅",
    subject: "국어",
    overallRating: 5,
    ratingContent: 5,
    ratingValue: 5,
    ratingManage: 0,
    title: "문학 기출 완전 정복, 마더텅이 최고",
    content: "문학 기출을 갈래별(시, 소설, 수필)로 정리해줘서 유형 학습이 정말 편해요. 과거 수능부터 최근 기출까지 폭넓게 수록되어 있고, 작품 해설이 정말 꼼꼼합니다. 두꺼운 편이지만 문학 공부 한 권으로 끝내고 싶다면 이 교재가 최고예요. 가격도 착하고요.",
    prosTagIds: ["기출_총정리", "가성비", "꼼꼼한_해설"],
    consTagIds: ["두꺼운_두께"],
    gradeLevel: "고3",
    gradeBefore: "3등급",
    gradeAfter: "1등급",
    studyDuration: "5개월",
    likes: 71,
    views: 802,
  },
  {
    type: "workbook",
    targetName: "절대등급 생명과학1 N제",
    publisher: "에듀기프트",
    subject: "생명과학",
    overallRating: 4,
    ratingContent: 5,
    ratingValue: 3,
    ratingManage: 0,
    title: "생명과학1 고난도 완성에 좋은 N제",
    content: "생명과학1 1등급 목표로 풀었어요. 기출에서 보기 힘든 킬러 유형 문제들이 많아서 실력을 끌어올리는 데 도움이 됐습니다. 난이도가 상당히 높아서 개념을 완전히 이해한 후에 푸는 게 좋아요. 가격이 좀 있지만 내용만큼은 최고 수준입니다.",
    prosTagIds: ["고난도_대비", "다양한_유형"],
    consTagIds: ["가격_높음", "난이도_높음"],
    gradeLevel: "N수생",
    gradeBefore: "2등급",
    gradeAfter: "1등급",
    studyDuration: "4개월",
    likes: 38,
    views: 435,
  },
  {
    type: "workbook",
    targetName: "쎈 수학 고등 수학1",
    publisher: "좋은책신사고",
    subject: "수학",
    overallRating: 4,
    ratingContent: 4,
    ratingValue: 5,
    ratingManage: 0,
    title: "수학 기본기 + 심화까지 한 권으로",
    content: "쎈 수학은 A~C단계로 나눠져서 실력에 맞게 단계적으로 풀 수 있어요. 문제 수가 엄청나게 많아서 충분히 연습할 수 있습니다. 쉬운 문제부터 어려운 문제까지 폭넓게 수록되어 있어서 어느 수준의 학생이든 활용하기 좋아요. 가격 대비 분량이 정말 좋습니다.",
    prosTagIds: ["단계별_학습", "가성비", "문제_다양"],
    consTagIds: ["너무_많은_문제수"],
    gradeLevel: "고1",
    gradeBefore: "4등급",
    gradeAfter: "2등급",
    studyDuration: "5개월",
    likes: 54,
    views: 617,
  },
  {
    type: "workbook",
    targetName: "수능특강 영어영역 (EBS)",
    publisher: "EBS",
    subject: "영어",
    overallRating: 3,
    ratingContent: 4,
    ratingValue: 5,
    ratingManage: 0,
    title: "연계는 되는데 재미는 없는 교재",
    content: "수능 영어 연계 대비로 당연히 봐야 하는 교재예요. 지문 수준이 실제 수능과 비슷하고, 다양한 유형이 수록되어 있습니다. 다만 혼자 공부하기에는 좀 지루하고 해설이 부실한 편이라, 강의와 함께 공부하는 걸 추천합니다. 연계 교재이니 선택이 아닌 필수입니다.",
    prosTagIds: ["수능_연계", "가성비"],
    consTagIds: ["해설_부실", "흥미도_낮음"],
    gradeLevel: "고3",
    gradeBefore: "2등급",
    gradeAfter: "1등급",
    studyDuration: "4개월",
    likes: 20,
    views: 248,
  },
  {
    type: "workbook",
    targetName: "타임 어택 수능 영어 실전모의고사",
    publisher: "에듀기프트",
    subject: "영어",
    overallRating: 5,
    ratingContent: 5,
    ratingValue: 4,
    ratingManage: 0,
    title: "실전 시간 관리 훈련에 최고",
    content: "영어 시험에서 시간이 부족해서 이 교재로 훈련했어요. 실제 수능과 비슷한 형태의 모의고사가 여러 회차 수록되어 있고, 시간 분배 전략도 알려줍니다. 풀다 보면 자연스럽게 시간 감각이 생겨요. 고3 수험생이라면 실전 대비로 강력 추천합니다.",
    prosTagIds: ["실전_대비", "시간_관리"],
    consTagIds: ["가격_보통"],
    gradeLevel: "고3",
    gradeBefore: "2등급",
    gradeAfter: "1등급",
    studyDuration: "2개월",
    likes: 44,
    views: 499,
  },
  {
    type: "workbook",
    targetName: "뉴런 수학 미적분 (현우진 저)",
    publisher: "메가스터디",
    subject: "수학",
    overallRating: 5,
    ratingContent: 5,
    ratingValue: 4,
    ratingManage: 0,
    title: "현우진 교재, 역대 최고의 미적분 교재",
    content: "뉴런 미적분은 강의와 함께 쓰면 진짜 시너지가 나요. 개념 설명이 직관적이고, 문제도 실전과 매우 유사합니다. 킬러 문제가 포함되어 있어서 수능에서 고난도 미적분 문제 대비도 됩니다. 미적분 선택한 수험생이라면 반드시 풀어야 할 교재입니다.",
    prosTagIds: ["고난도_대비", "강의_연계", "실전_대비"],
    consTagIds: ["가격_보통"],
    gradeLevel: "고3",
    gradeBefore: "2등급",
    gradeAfter: "1등급",
    studyDuration: "5개월",
    likes: 67,
    views: 754,
  },
  {
    type: "workbook",
    targetName: "한국사 수능 개념완성 (천재교육)",
    publisher: "천재교육",
    subject: "한국사",
    overallRating: 4,
    ratingContent: 4,
    ratingValue: 4,
    ratingManage: 0,
    title: "한국사 개념 정리에 깔끔한 교재",
    content: "수능 한국사 개념 정리를 위해 구입했어요. 시대별로 개념이 깔끔하게 정리되어 있고, 사진 자료와 지도가 풍부해서 이해하기 쉽습니다. 기출 문제도 함께 수록되어 있어서 개념 확인 문제로 활용하기 좋아요. 한국사 기초를 다지는 학생들에게 적합합니다.",
    prosTagIds: ["깔끔한_정리", "자료_풍부"],
    consTagIds: ["심화_부족"],
    gradeLevel: "고2",
    gradeBefore: "5등급",
    gradeAfter: "3등급",
    studyDuration: "2개월",
    likes: 26,
    views: 298,
  },
  {
    type: "workbook",
    targetName: "오감도 수능 국어 화법과작문",
    publisher: "키출판사",
    subject: "국어",
    overallRating: 4,
    ratingContent: 4,
    ratingValue: 4,
    ratingManage: 0,
    title: "화법작문 집중 대비에 딱인 교재",
    content: "국어에서 화법과 작문 파트를 집중적으로 공략하려고 샀어요. 유형별 분류가 잘 되어 있고, 각 유형에 대한 풀이 전략도 알려줘서 효율적으로 공부할 수 있었습니다. 다만 독서·문학은 다루지 않으니 화법작문 보완용으로만 쓰기 좋아요.",
    prosTagIds: ["유형_정리", "풀이_전략"],
    consTagIds: ["범위_제한"],
    gradeLevel: "고3",
    gradeBefore: "3등급",
    gradeAfter: "2등급",
    studyDuration: "1개월",
    likes: 18,
    views: 213,
  },
  {
    type: "workbook",
    targetName: "지구과학1 N제 (수능 기출과 변형)",
    publisher: "이투스북",
    subject: "지구과학",
    overallRating: 4,
    ratingContent: 4,
    ratingValue: 4,
    ratingManage: 0,
    title: "지구과학 심화 대비, 기출+변형 구성 좋음",
    content: "지구과학1 1등급 목표로 기출 외에 변형 문제도 연습하고 싶어서 샀어요. 기출 문제와 유사한 변형 문제가 함께 수록되어 있어서 새로운 유형에 당황하지 않는 연습이 됩니다. 난이도가 중상 수준이라 기본기를 갖춘 후에 활용하면 좋습니다.",
    prosTagIds: ["기출_변형", "실전_대비"],
    consTagIds: ["기본기_필요"],
    gradeLevel: "고3",
    gradeBefore: "3등급",
    gradeAfter: "2등급",
    studyDuration: "3개월",
    likes: 22,
    views: 253,
  },
  {
    type: "workbook",
    targetName: "하이탑 생명과학1 (완자)",
    publisher: "비상교육",
    subject: "생명과학",
    overallRating: 3,
    ratingContent: 3,
    ratingValue: 4,
    ratingManage: 0,
    title: "개념 교재로는 좋은데 수능 대비용으로는 부족",
    content: "생명과학1 개념 정리용으로 구입했어요. 그림이 많고 설명이 쉬워서 개념 이해하기는 좋아요. 다만 문제가 내신 수준이라 수능 대비로는 좀 부족한 느낌입니다. 개념을 처음 배울 때 활용하고, 이후에 N제나 기출로 넘어가는 것을 추천드려요.",
    prosTagIds: ["개념_충실", "그림_풍부"],
    consTagIds: ["수능_대비_부족", "내신용"],
    gradeLevel: "고1",
    gradeBefore: "4등급",
    gradeAfter: "3등급",
    studyDuration: "2개월",
    likes: 11,
    views: 147,
  },
  {
    type: "workbook",
    targetName: "100발 100중 물리학1 기출문제집",
    publisher: "에듀기프트",
    subject: "물리학",
    overallRating: 5,
    ratingContent: 5,
    ratingValue: 5,
    ratingManage: 0,
    title: "물리1 기출 완전정복, 가성비 최강",
    content: "역대 물리학1 수능·모의고사 기출을 단원별로 정리해뒀어요. 해설이 정말 꼼꼼하고, 오답 선지까지 분석해줘서 실력이 확실히 늘어요. 가격 대비 문제 수가 엄청나서 가성비도 최고입니다. 물리1로 수능 보는 학생이라면 반드시 풀어야 할 교재입니다.",
    prosTagIds: ["기출_총정리", "가성비", "꼼꼼한_해설"],
    consTagIds: [],
    gradeLevel: "고3",
    gradeBefore: "3등급",
    gradeAfter: "1등급",
    studyDuration: "5개월",
    likes: 59,
    views: 661,
  },
  {
    type: "workbook",
    targetName: "시그마 사회·문화 개념완성",
    publisher: "교학사",
    subject: "사회문화",
    overallRating: 4,
    ratingContent: 4,
    ratingValue: 4,
    ratingManage: 0,
    title: "사회문화 개념 빠르게 정리하기 좋아요",
    content: "사회문화 개념 정리를 빠르게 하고 싶어서 샀어요. 핵심 개념이 압축적으로 정리되어 있어서 효율적으로 복습할 수 있습니다. 다만 처음 개념을 배우는 학생에게는 좀 부족할 수 있어요. 기본 개념을 익힌 뒤 정리·복습용으로 활용하기 딱입니다.",
    prosTagIds: ["핵심_압축", "효율적"],
    consTagIds: ["초보자_부적합"],
    gradeLevel: "고2",
    gradeBefore: "4등급",
    gradeAfter: "3등급",
    studyDuration: "2개월",
    likes: 17,
    views: 204,
  },
  {
    type: "workbook",
    targetName: "일등급 수능 수학 킬러 문항 공략",
    publisher: "에듀기프트",
    subject: "수학",
    overallRating: 4,
    ratingContent: 5,
    ratingValue: 3,
    ratingManage: 0,
    title: "킬러 문항 극복, 1등급을 향한 마지막 관문",
    content: "수능 수학에서 킬러 문항(28·29·30번)이 늘 발목을 잡아서 구입했어요. 역대 킬러 문항들을 유형별로 분류해두고, 각 유형의 접근 전략을 알려줘서 도움이 됐습니다. 매우 어렵지만 반복해서 풀다 보면 패턴이 보여요. 2등급에서 1등급 목표하는 수험생에게 추천합니다.",
    prosTagIds: ["고난도_대비", "유형_분류"],
    consTagIds: ["가격_높음", "난이도_매우_높음"],
    gradeLevel: "N수생",
    gradeBefore: "2등급",
    gradeAfter: "1등급",
    studyDuration: "3개월",
    likes: 48,
    views: 541,
  },
  {
    type: "workbook",
    targetName: "그라핀 미적분 기출의 파급효과",
    publisher: "그라핀",
    subject: "수학",
    overallRating: 5,
    ratingContent: 5,
    ratingValue: 4,
    ratingManage: 0,
    title: "미적분 기출 해설의 새로운 기준",
    content: "파급효과는 단순 기출 수록이 아니라, 기출 풀이를 상세하게 분석해준다는 점이 달라요. 풀이 방법이 여러 가지 제시되고, 최적의 풀이법도 알려줘서 시험장에서 빠르게 풀 수 있게 됩니다. 미적분에서 1등급 목표로 깊이 공부하고 싶은 학생에게 강력 추천합니다.",
    prosTagIds: ["꼼꼼한_해설", "다양한_풀이", "실전_대비"],
    consTagIds: ["가격_높음"],
    gradeLevel: "N수생",
    gradeBefore: "2등급",
    gradeAfter: "1등급",
    studyDuration: "4개월",
    likes: 73,
    views: 822,
  },
  {
    type: "workbook",
    targetName: "화학1 수능 기출문제집 (마더텅)",
    publisher: "마더텅",
    subject: "화학",
    overallRating: 5,
    ratingContent: 5,
    ratingValue: 5,
    ratingManage: 0,
    title: "화학1 기출 이 교재 하나로 완벽 대비",
    content: "마더텅 화학1 기출문제집은 역대 수능과 모의고사 기출을 빠짐없이 담고 있어요. 단원별로 정리되어 있어서 약한 단원을 집중적으로 공부하기 좋습니다. 해설이 매우 꼼꼼하고 자세해서 혼자 공부해도 이해가 됩니다. 화학1 수능 준비에 필수 교재입니다.",
    prosTagIds: ["기출_총정리", "가성비", "꼼꼼한_해설"],
    consTagIds: [],
    gradeLevel: "고3",
    gradeBefore: "4등급",
    gradeAfter: "2등급",
    studyDuration: "4개월",
    likes: 61,
    views: 688,
  },
  {
    type: "workbook",
    targetName: "최적화 수능 영어 구문독해 200제",
    publisher: "쎄듀",
    subject: "영어",
    overallRating: 4,
    ratingContent: 4,
    ratingValue: 4,
    ratingManage: 0,
    title: "영어 구문 분석 실력 올려주는 교재",
    content: "영어 지문을 읽을 때 구조 분석이 잘 안 돼서 이 교재로 공부했어요. 200개의 구문 독해 문제를 통해 다양한 문장 구조에 익숙해질 수 있습니다. 해설에서 문장 구조 분석과 직역/의역이 함께 제공되어 이해하기 쉬워요. 영어 독해 기본기를 다지는 데 추천합니다.",
    prosTagIds: ["구문_분석", "충실한_해설"],
    consTagIds: [],
    gradeLevel: "고2",
    gradeBefore: "4등급",
    gradeAfter: "3등급",
    studyDuration: "2개월",
    likes: 31,
    views: 357,
  },
  {
    type: "workbook",
    targetName: "수능 국어 독서 독해 훈련 300제",
    publisher: "키출판사",
    subject: "국어",
    overallRating: 4,
    ratingContent: 4,
    ratingValue: 4,
    ratingManage: 0,
    title: "독서 독해 연습에 분량이 충분한 교재",
    content: "국어 비문학 독해 연습이 부족해서 이 교재로 추가 훈련을 했어요. 300문항이 수록되어 있어서 분량이 충분하고, 다양한 지문 유형이 포함되어 있습니다. 해설도 지문 분석 위주로 나와서 독해 능력이 체계적으로 향상됩니다. 독서 파트가 약한 학생들에게 추천합니다.",
    prosTagIds: ["풍부한_문제수", "다양한_지문"],
    consTagIds: ["단순_반복_위주"],
    gradeLevel: "고2",
    gradeBefore: "4등급",
    gradeAfter: "3등급",
    studyDuration: "3개월",
    likes: 23,
    views: 261,
  },
];

// ─── Academy Reviews (학원) ───────────────────────────────────────────────────
const academyReviews = [
  {
    type: "academy",
    targetName: "시대인재 강남관",
    publisher: null,
    instructor: null,
    platform: null,
    subject: "수학",
    region: "서울",
    district: "강남구",
    overallRating: 5,
    ratingContent: 5,
    ratingValue: 3,
    ratingManage: 5,
    title: "최상위 학원답게 관리가 정말 철저해요",
    content: "시대인재 강남관 다니면서 수학 1등급 만들었어요. 선생님들 수업 수준이 높고, 매주 시험과 오답 점검이 이루어져서 스스로 공부 안 하면 도태됩니다. 관리가 워낙 엄격해서 처음에는 힘들었는데, 덕분에 공부 습관이 잡혔어요. 가격이 비싸서 부담은 되지만 결과는 확실합니다.",
    prosTagIds: ["수준_높은_수업", "철저한_관리"],
    consTagIds: ["가격_높음", "경쟁_치열"],
    gradeLevel: "고3",
    gradeBefore: "2등급",
    gradeAfter: "1등급",
    studyDuration: "1년",
    likes: 67,
    views: 745,
  },
  {
    type: "academy",
    targetName: "대치 종로학원 수학",
    publisher: null,
    instructor: null,
    platform: null,
    subject: "수학",
    region: "서울",
    district: "강남구",
    overallRating: 4,
    ratingContent: 4,
    ratingValue: 3,
    ratingManage: 4,
    title: "체계적인 커리큘럼, 대형 학원의 장점",
    content: "종로학원 대치에서 고3 수학 들었어요. 체계적인 커리큘럼이 있어서 일정에 맞게 공부할 수 있고, 강사진도 실력 있는 분들이에요. 다만 대형 학원이라 개인 관리가 좀 아쉽고, 질문이 자유롭지 않은 편이에요. 자기 주도 학습이 되는 학생들에게 더 맞는 환경입니다.",
    prosTagIds: ["체계적인_커리큘럼", "실력있는_강사"],
    consTagIds: ["개인_관리_부족", "질문_어려움"],
    gradeLevel: "고3",
    gradeBefore: "3등급",
    gradeAfter: "2등급",
    studyDuration: "6개월",
    likes: 32,
    views: 388,
  },
  {
    type: "academy",
    targetName: "목동 청솔학원 국어",
    publisher: null,
    instructor: null,
    platform: null,
    subject: "국어",
    region: "서울",
    district: "양천구",
    overallRating: 5,
    ratingContent: 5,
    ratingValue: 4,
    ratingManage: 4,
    title: "국어 1등급 만들어준 학원, 적극 추천",
    content: "목동 청솔에서 국어 강의 들었는데 진짜 좋았어요. 선생님이 문학·독서·화법작문 모두 체계적으로 가르쳐주시고, 매주 모의고사를 보면서 실전 감각을 유지할 수 있어요. 개인별 약점 분석도 해줘서 효율적으로 공부할 수 있었습니다. 국어 때문에 고민이라면 강추합니다.",
    prosTagIds: ["체계적인_커리큘럼", "실전_대비", "개인_관리"],
    consTagIds: [],
    gradeLevel: "고3",
    gradeBefore: "3등급",
    gradeAfter: "1등급",
    studyDuration: "1년",
    likes: 55,
    views: 621,
  },
  {
    type: "academy",
    targetName: "강남 씨앤씨학원 영어",
    publisher: null,
    instructor: null,
    platform: null,
    subject: "영어",
    region: "서울",
    district: "강남구",
    overallRating: 4,
    ratingContent: 4,
    ratingValue: 4,
    ratingManage: 4,
    title: "영어 독해 실력 확실히 올려주는 학원",
    content: "씨앤씨에서 영어 독해 수업 들었어요. 구문 분석부터 지문 독해 전략까지 꼼꼼하게 가르쳐주시고, 매 수업마다 지문 숙제가 있어서 읽는 양이 늘어납니다. 가격이 부담되지만 실력은 확실히 올라요. 모의고사 영어 2등급 → 1등급 만들었습니다.",
    prosTagIds: ["독해_전략", "충분한_연습"],
    consTagIds: ["가격_높음", "숙제_많음"],
    gradeLevel: "고2",
    gradeBefore: "2등급",
    gradeAfter: "1등급",
    studyDuration: "8개월",
    likes: 41,
    views: 465,
  },
  {
    type: "academy",
    targetName: "노량진 이투스247 N수생관",
    publisher: null,
    instructor: null,
    platform: null,
    subject: "수학",
    region: "서울",
    district: "동작구",
    overallRating: 4,
    ratingContent: 4,
    ratingValue: 4,
    ratingManage: 5,
    title: "N수생이라면 노량진 재종반, 관리가 핵심",
    content: "N수를 결심하고 노량진 이투스247 재종반에 등록했어요. 아침부터 저녁까지 스케줄 관리를 해줘서 혼자서는 흐트러지기 쉬운 페이스를 유지할 수 있었습니다. 강의 수준도 높고, 동기 부여도 잘 되는 환경이에요. 마음잡고 수능 다시 준비하려는 분들께 추천합니다.",
    prosTagIds: ["철저한_관리", "동기_부여", "재종반"],
    consTagIds: ["경쟁_치열"],
    gradeLevel: "N수생",
    gradeBefore: "3등급",
    gradeAfter: "1등급",
    studyDuration: "1년",
    likes: 49,
    views: 557,
  },
  {
    type: "academy",
    targetName: "분당 수내동 스카이수학학원",
    publisher: null,
    instructor: null,
    platform: null,
    subject: "수학",
    region: "경기",
    district: "성남시",
    overallRating: 5,
    ratingContent: 5,
    ratingValue: 4,
    ratingManage: 5,
    title: "분당에서 손꼽히는 수학 학원, 강추",
    content: "수내동에 있는 스카이수학학원 정말 좋아요. 원장 선생님이 직접 가르치시고, 수업 후 질문 타임도 충분히 줘서 모르는 것을 그날그날 해결할 수 있어요. 수준별 반 편성이 잘 되어 있어서 자기 수준에 맞는 수업을 들을 수 있습니다. 분당권 학생들한테 추천드려요.",
    prosTagIds: ["수준별_반편성", "질문_가능", "친절한_관리"],
    consTagIds: [],
    gradeLevel: "고2",
    gradeBefore: "3등급",
    gradeAfter: "1등급",
    studyDuration: "1년",
    likes: 38,
    views: 431,
  },
  {
    type: "academy",
    targetName: "부산 해운대 탑클래스학원",
    publisher: null,
    instructor: null,
    platform: null,
    subject: "수학",
    region: "부산",
    district: "해운대구",
    overallRating: 4,
    ratingContent: 4,
    ratingValue: 4,
    ratingManage: 4,
    title: "부산 해운대에서 수학 공부하고 싶다면",
    content: "해운대 탑클래스학원에서 수학 들었어요. 선생님들이 꼼꼼하게 가르쳐주시고, 매주 단원 테스트를 통해 이해도를 점검해줍니다. 교재도 잘 선정되어 있고, 자습실 환경도 쾌적해요. 부산에서 이 정도 수준의 학원이면 충분히 만족스럽습니다.",
    prosTagIds: ["꼼꼼한_수업", "쾌적한_자습실", "주기적_테스트"],
    consTagIds: [],
    gradeLevel: "고3",
    gradeBefore: "4등급",
    gradeAfter: "2등급",
    studyDuration: "6개월",
    likes: 27,
    views: 313,
  },
  {
    type: "academy",
    targetName: "대구 수성구 에이스학원 영어",
    publisher: null,
    instructor: null,
    platform: null,
    subject: "영어",
    region: "대구",
    district: "수성구",
    overallRating: 5,
    ratingContent: 5,
    ratingValue: 4,
    ratingManage: 5,
    title: "대구 수성구 영어학원 중 최고예요",
    content: "에이스학원에서 고3 수능 영어 들었어요. 선생님이 지문 분석과 어휘 정리를 꼼꼼하게 해주셔서 영어 독해 실력이 많이 올랐습니다. 주1회 모의고사를 봐서 실전 감각도 유지할 수 있어요. 수성구 내에서 영어 학원 고민이라면 강력 추천드립니다.",
    prosTagIds: ["지문_분석", "실전_대비", "철저한_관리"],
    consTagIds: [],
    gradeLevel: "고3",
    gradeBefore: "3등급",
    gradeAfter: "1등급",
    studyDuration: "1년",
    likes: 33,
    views: 379,
  },
  {
    type: "academy",
    targetName: "인천 부평 명문수학학원",
    publisher: null,
    instructor: null,
    platform: null,
    subject: "수학",
    region: "인천",
    district: "부평구",
    overallRating: 4,
    ratingContent: 4,
    ratingValue: 5,
    ratingManage: 4,
    title: "가성비 좋은 인천 수학학원",
    content: "부평에 있는 명문수학학원 가성비가 정말 좋아요. 비슷한 수준의 강의를 서울 강남보다 훨씬 저렴하게 들을 수 있습니다. 선생님도 친절하고, 개인 질문도 수업 후에 충분히 할 수 있어요. 자체 제작 교재도 내용이 충실해서 따로 구입할 필요가 없었어요.",
    prosTagIds: ["가성비", "친절한_선생님", "자체_교재"],
    consTagIds: [],
    gradeLevel: "고2",
    gradeBefore: "4등급",
    gradeAfter: "2등급",
    studyDuration: "1년",
    likes: 29,
    views: 337,
  },
  {
    type: "academy",
    targetName: "광주 상무지구 JY국어학원",
    publisher: null,
    instructor: null,
    platform: null,
    subject: "국어",
    region: "광주",
    district: "서구",
    overallRating: 5,
    ratingContent: 5,
    ratingValue: 4,
    ratingManage: 5,
    title: "광주에서 국어 1등급 만든 학원",
    content: "JY국어학원에서 수능 국어 전 영역을 공부했어요. 선생님이 독서, 문학, 화법작문 각각 전략을 체계적으로 가르쳐주셔서 유형별 대응이 가능해졌습니다. 매월 자체 모의고사도 진행하고, 결과를 바탕으로 개인 피드백도 줘요. 광주 학원 중에서 국어는 여기가 최고입니다.",
    prosTagIds: ["체계적_커리큘럼", "개인_피드백", "실전_대비"],
    consTagIds: [],
    gradeLevel: "고3",
    gradeBefore: "4등급",
    gradeAfter: "1등급",
    studyDuration: "1년",
    likes: 44,
    views: 497,
  },
  {
    type: "academy",
    targetName: "대전 둔산동 대성학원",
    publisher: null,
    instructor: null,
    platform: null,
    subject: "수학",
    region: "대전",
    district: "서구",
    overallRating: 4,
    ratingContent: 4,
    ratingValue: 4,
    ratingManage: 3,
    title: "대전에서 오랜 역사의 학원, 신뢰할 수 있어요",
    content: "대성학원 둔산관에서 수학 들었어요. 오랜 역사만큼 커리큘럼이 탄탄하고, 강사진도 안정적이에요. 다만 학생 수가 많아서 개인적인 관리가 다소 부족한 편이에요. 자기 주도적으로 공부할 수 있는 학생이라면 강의력만으로도 충분히 도움이 됩니다.",
    prosTagIds: ["탄탄한_커리큘럼", "신뢰_있는_강사진"],
    consTagIds: ["개인_관리_부족", "많은_학생수"],
    gradeLevel: "고3",
    gradeBefore: "3등급",
    gradeAfter: "2등급",
    studyDuration: "6개월",
    likes: 21,
    views: 249,
  },
  {
    type: "academy",
    targetName: "강남 대치 생명과학 전문 BIO학원",
    publisher: null,
    instructor: null,
    platform: null,
    subject: "생명과학",
    region: "서울",
    district: "강남구",
    overallRating: 5,
    ratingContent: 5,
    ratingValue: 3,
    ratingManage: 5,
    title: "생명과학1 특화 학원, 1등급 메이커",
    content: "생명과학1 전문 학원이라서 수업 수준이 정말 높아요. 생명과학1 고난도 유형을 다 다루고, 자체 문제도 정말 좋습니다. 선생님이 기출 분석에 특화되어 있어서 수능 대비가 완벽하게 됩니다. 가격은 비싼 편이지만 생명과학으로 1등급 목표라면 가치 있는 투자예요.",
    prosTagIds: ["전문적_수업", "고난도_대비", "기출_분석"],
    consTagIds: ["가격_높음"],
    gradeLevel: "N수생",
    gradeBefore: "2등급",
    gradeAfter: "1등급",
    studyDuration: "1년",
    likes: 52,
    views: 591,
  },
  {
    type: "academy",
    targetName: "일산 후곡 수성학원 수학",
    publisher: null,
    instructor: null,
    platform: null,
    subject: "수학",
    region: "경기",
    district: "고양시",
    overallRating: 4,
    ratingContent: 4,
    ratingValue: 5,
    ratingManage: 4,
    title: "일산에서 가성비 최고 수학 학원",
    content: "후곡에 있는 수성학원 가성비 정말 좋아요. 강남 학원 부럽지 않은 수준의 수업인데 가격은 절반 이하예요. 선생님이 개념부터 심화까지 꼼꼼하게 설명해주시고, 개인 질문도 잘 받아줍니다. 일산·파주 학생들한테 강력 추천드립니다.",
    prosTagIds: ["가성비", "꼼꼼한_수업", "질문_가능"],
    consTagIds: [],
    gradeLevel: "고2",
    gradeBefore: "4등급",
    gradeAfter: "2등급",
    studyDuration: "1년",
    likes: 35,
    views: 398,
  },
  {
    type: "academy",
    targetName: "수원 영통 TOP영어학원",
    publisher: null,
    instructor: null,
    platform: null,
    subject: "영어",
    region: "경기",
    district: "수원시",
    overallRating: 4,
    ratingContent: 5,
    ratingValue: 4,
    ratingManage: 4,
    title: "수원에서 영어 독해 전문 학원으로 강추",
    content: "영통에 있는 TOP영어학원 정말 좋아요. 독해 구문 분석 중심으로 가르쳐주셔서 단순 해석이 아니라 문장 구조를 이해하며 읽는 습관이 생겼어요. 어휘 암기 관리도 해줘서 단어 실력도 덩달아 늘었습니다. 수원 영어 학원 중에서 추천하고 싶은 곳 1위입니다.",
    prosTagIds: ["구문_분석", "어휘_관리", "체계적"],
    consTagIds: [],
    gradeLevel: "고1",
    gradeBefore: "4등급",
    gradeAfter: "2등급",
    studyDuration: "1년",
    likes: 28,
    views: 321,
  },
  {
    type: "academy",
    targetName: "의정부 민락 스카이과학학원",
    publisher: null,
    instructor: null,
    platform: null,
    subject: "화학",
    region: "경기",
    district: "의정부시",
    overallRating: 3,
    ratingContent: 4,
    ratingValue: 4,
    ratingManage: 3,
    title: "나쁘지 않지만 특별히 뛰어나지도 않아요",
    content: "화학 수업을 들었는데 평범한 수준이에요. 개념 설명은 충실하지만 심화 문제 대비가 좀 부족해요. 관리도 보통 수준이고, 의정부 내에서 선택지가 많지 않아서 다니는 정도입니다. 가격은 적당해서 기본기 쌓기에는 좋은 것 같아요.",
    prosTagIds: ["개념_충실", "적당한_가격"],
    consTagIds: ["심화_부족", "관리_평범"],
    gradeLevel: "고2",
    gradeBefore: "4등급",
    gradeAfter: "3등급",
    studyDuration: "6개월",
    likes: 9,
    views: 118,
  },
  {
    type: "academy",
    targetName: "서울 노원구 하이탑수학학원",
    publisher: null,
    instructor: null,
    platform: null,
    subject: "수학",
    region: "서울",
    district: "노원구",
    overallRating: 4,
    ratingContent: 4,
    ratingValue: 4,
    ratingManage: 4,
    title: "노원에서 수학 잘 가르치는 학원",
    content: "노원구에서 수학 학원 찾다가 하이탑 가게 됐어요. 선생님이 수업을 꼼꼼하게 해주시고, 학생 개인 수준에 맞게 숙제도 따로 내줘서 좋았어요. 매달 테스트로 성취도를 확인하고, 부진한 부분은 별도 보충해줍니다. 강남 학원보다 접근성도 좋고 가성비도 좋습니다.",
    prosTagIds: ["개인_맞춤", "보충_수업", "접근성"],
    consTagIds: [],
    gradeLevel: "고1",
    gradeBefore: "3등급",
    gradeAfter: "2등급",
    studyDuration: "1년",
    likes: 24,
    views: 278,
  },
  {
    type: "academy",
    targetName: "대치동 SKY물리학원",
    publisher: null,
    instructor: null,
    platform: null,
    subject: "물리학",
    region: "서울",
    district: "강남구",
    overallRating: 5,
    ratingContent: 5,
    ratingValue: 3,
    ratingManage: 5,
    title: "물리학 1등급 전용 학원, 가격은 세지만 결과도 세",
    content: "물리학1을 선택하고 SKY물리학원에 등록했어요. 수업 수준이 타 학원보다 월등히 높고, 킬러 문항 풀이 노하우를 제대로 배울 수 있어요. 매주 시험과 오답 분석이 이루어지고, 1:1 질문도 가능합니다. 가격이 상당히 높지만 그만큼 결과가 나오는 학원입니다.",
    prosTagIds: ["수준_높은_수업", "킬러_문항_대비", "1대1_질문"],
    consTagIds: ["가격_높음"],
    gradeLevel: "고3",
    gradeBefore: "3등급",
    gradeAfter: "1등급",
    studyDuration: "1년",
    likes: 58,
    views: 654,
  },
  {
    type: "academy",
    targetName: "마포 합정 국어전문 A+학원",
    publisher: null,
    instructor: null,
    platform: null,
    subject: "국어",
    region: "서울",
    district: "마포구",
    overallRating: 4,
    ratingContent: 5,
    ratingValue: 4,
    ratingManage: 4,
    title: "합정·망원에서 국어 공부하려면 이 학원",
    content: "A+국어학원 수업 퀄리티가 정말 높아요. 선생님이 국어 교육 전공자이셔서 수능 국어를 학문적으로 접근해서 가르쳐주시는데, 이해가 확실히 됩니다. 강남만큼 유명하지는 않지만 수업 내용은 절대 뒤처지지 않아요. 마포·서대문 학생들한테 추천합니다.",
    prosTagIds: ["수준_높은_수업", "전문성"],
    consTagIds: ["접근성_보통"],
    gradeLevel: "고2",
    gradeBefore: "3등급",
    gradeAfter: "2등급",
    studyDuration: "8개월",
    likes: 19,
    views: 226,
  },
  {
    type: "academy",
    targetName: "청주 산남동 플러스수학학원",
    publisher: null,
    instructor: null,
    platform: null,
    subject: "수학",
    region: "충북",
    district: "청주시",
    overallRating: 4,
    ratingContent: 4,
    ratingValue: 5,
    ratingManage: 4,
    title: "청주에서 성실하게 가르쳐주는 수학 학원",
    content: "플러스수학학원 원장 선생님이 직접 가르치셔서 수업 퀄리티가 일정하고 높아요. 개념 설명이 꼼꼼하고, 학생 수준에 맞는 문제를 골라서 내주셔서 효율적으로 공부했습니다. 가격도 저렴하고, 시설도 깔끔해요. 청주 학생들한테 강추드립니다.",
    prosTagIds: ["원장_직강", "개인_맞춤", "가성비"],
    consTagIds: [],
    gradeLevel: "고1",
    gradeBefore: "4등급",
    gradeAfter: "2등급",
    studyDuration: "1년",
    likes: 22,
    views: 257,
  },
  {
    type: "academy",
    targetName: "강남 대치 화학전문 케미스트리학원",
    publisher: null,
    instructor: null,
    platform: null,
    subject: "화학",
    region: "서울",
    district: "강남구",
    overallRating: 5,
    ratingContent: 5,
    ratingValue: 3,
    ratingManage: 5,
    title: "화학 1등급은 여기서, 타협 없는 수업",
    content: "케미스트리학원 수업이 정말 빡세요. 매주 단원 테스트에 불통과하면 추가 시험을 봐야 해서 절대 안이하게 공부할 수 없어요. 그 덕분에 화학 실력이 확실히 올랐습니다. 선생님이 기출 분석을 정말 날카롭게 해줘서 수능에서 만점 목표하는 학생들에게 강력 추천합니다.",
    prosTagIds: ["철저한_관리", "기출_분석", "엄격한_기준"],
    consTagIds: ["가격_높음", "강도_높음"],
    gradeLevel: "고3",
    gradeBefore: "2등급",
    gradeAfter: "1등급",
    studyDuration: "1년",
    likes: 61,
    views: 689,
  },
  {
    type: "academy",
    targetName: "부천 심곡본동 영재수학학원",
    publisher: null,
    instructor: null,
    platform: null,
    subject: "수학",
    region: "경기",
    district: "부천시",
    overallRating: 4,
    ratingContent: 4,
    ratingValue: 5,
    ratingManage: 3,
    title: "부천에서 내신·수능 둘 다 잡는 학원",
    content: "내신 대비와 수능 대비를 모두 해주는 학원이에요. 커리큘럼이 내신 기간에는 내신 위주, 그 외 기간에는 수능 수학 위주로 유연하게 바뀌어서 좋아요. 가격도 적당하고, 선생님도 친절합니다. 관리는 조금 자율에 맡기는 편이라, 스스로 공부 잘 하는 학생에게 더 맞는 것 같아요.",
    prosTagIds: ["내신_수능_병행", "가성비", "친절한_선생님"],
    consTagIds: ["관리_자율"],
    gradeLevel: "고2",
    gradeBefore: "3등급",
    gradeAfter: "2등급",
    studyDuration: "1년",
    likes: 16,
    views: 189,
  },
  {
    type: "academy",
    targetName: "강남 대치 생기부 전략 입시컨설팅",
    publisher: null,
    instructor: null,
    platform: null,
    subject: "입시상담",
    region: "서울",
    district: "강남구",
    overallRating: 5,
    ratingContent: 5,
    ratingValue: 4,
    ratingManage: 5,
    title: "학생부 관리와 입시 전략, 진짜 도움 됐어요",
    content: "생기부 전략부터 수시 지원 전략까지 정말 꼼꼼하게 컨설팅해줬어요. 저의 성적과 스펙에 맞는 대학·학과를 분석해주고, 자소서 작성부터 면접 준비까지 전반적으로 도와줬습니다. 덕분에 원하는 대학에 수시로 합격했어요. 비용이 들지만 충분히 가치 있는 투자입니다.",
    prosTagIds: ["개인_맞춤_전략", "자소서_도움", "면접_준비"],
    consTagIds: ["가격_높음"],
    gradeLevel: "고3",
    gradeBefore: null,
    gradeAfter: null,
    studyDuration: "6개월",
    likes: 77,
    views: 872,
  },
  {
    type: "academy",
    targetName: "목동 수학의 정석 학원",
    publisher: null,
    instructor: null,
    platform: null,
    subject: "수학",
    region: "서울",
    district: "양천구",
    overallRating: 5,
    ratingContent: 5,
    ratingValue: 4,
    ratingManage: 5,
    title: "목동 수학 학원 중 최상위, 결과가 증명해요",
    content: "목동에서 오랫동안 명성을 유지하고 있는 학원이에요. 선생님들 수업 수준이 정말 높고, 매주 수준별 시험으로 실력을 점검합니다. 학생들 성적 관리를 체계적으로 해줘서 목표 점수 달성에 집중할 수 있어요. 목동권 학생이라면 한 번쯤 들어본 학원입니다.",
    prosTagIds: ["수준_높은_수업", "체계적_관리", "명성"],
    consTagIds: ["가격_높음", "경쟁_치열"],
    gradeLevel: "고3",
    gradeBefore: "2등급",
    gradeAfter: "1등급",
    studyDuration: "1년",
    likes: 64,
    views: 723,
  },
  {
    type: "academy",
    targetName: "전주 효자동 베스트국어학원",
    publisher: null,
    instructor: null,
    platform: null,
    subject: "국어",
    region: "전북",
    district: "전주시",
    overallRating: 4,
    ratingContent: 4,
    ratingValue: 5,
    ratingManage: 4,
    title: "전주에서 국어 공부, 가성비 좋은 학원",
    content: "전주에서 수능 국어 공부하려고 여러 학원을 알아봤는데, 베스트국어학원이 제일 좋았어요. 선생님이 지문 분석법을 체계적으로 가르쳐주시고, 모의고사도 자주 봐서 실전 감각을 유지할 수 있었습니다. 가격도 서울 학원들보다 훨씬 저렴해서 가성비도 최고예요.",
    prosTagIds: ["가성비", "체계적_수업", "실전_대비"],
    consTagIds: [],
    gradeLevel: "고3",
    gradeBefore: "4등급",
    gradeAfter: "2등급",
    studyDuration: "8개월",
    likes: 18,
    views: 213,
  },
  {
    type: "academy",
    targetName: "안양 평촌 메가영어학원",
    publisher: null,
    instructor: null,
    platform: null,
    subject: "영어",
    region: "경기",
    district: "안양시",
    overallRating: 4,
    ratingContent: 4,
    ratingValue: 4,
    ratingManage: 4,
    title: "평촌에서 영어 학원 고민이라면 여기로",
    content: "메가영어학원에서 수능 영어 전 범위를 공부했어요. 독해, 어법, 어휘를 고루 다뤄줘서 영어 전반적인 실력이 올랐습니다. 정기적인 모의고사와 개인 성적 피드백도 제공해주고, 질문도 편하게 할 수 있어서 좋아요. 평촌 영어 학원 중에서 추천하고 싶은 곳입니다.",
    prosTagIds: ["전범위_수업", "개인_피드백", "질문_가능"],
    consTagIds: [],
    gradeLevel: "고2",
    gradeBefore: "3등급",
    gradeAfter: "2등급",
    studyDuration: "1년",
    likes: 21,
    views: 243,
  },
  {
    type: "academy",
    targetName: "성남 분당구 지구과학 전문 GEO학원",
    publisher: null,
    instructor: null,
    platform: null,
    subject: "지구과학",
    region: "경기",
    district: "성남시",
    overallRating: 5,
    ratingContent: 5,
    ratingValue: 4,
    ratingManage: 5,
    title: "지구과학 1등급 맞으려면 GEO학원으로",
    content: "지구과학 전문 학원이라 수업 수준이 다른 일반 학원과 달라요. 기출 분석이 정말 꼼꼼하고, 선생님이 출제 경향을 정확하게 짚어줍니다. 매달 자체 시험으로 단원별 실력을 확인하고, 오답 분석도 상세하게 해줘요. 지구과학으로 상위 등급 노리는 학생에게 강력 추천합니다.",
    prosTagIds: ["전문적_수업", "기출_분석", "철저한_관리"],
    consTagIds: ["가격_보통"],
    gradeLevel: "고3",
    gradeBefore: "3등급",
    gradeAfter: "1등급",
    studyDuration: "1년",
    likes: 46,
    views: 521,
  },
];

async function main() {
  console.log("=== 커뮤니티 리뷰 시드 데이터 삽입 시작 ===");

  // Get first user from DB to use as author
  const allUsers = await db.select().from(users).limit(1);
  if (allUsers.length === 0) {
    console.error("❌ 사용자가 없습니다. 먼저 로그인해서 사용자를 생성하세요.");
    process.exit(1);
  }
  const seedUserId = allUsers[0].id;
  console.log(`✓ 시드 사용자 ID: ${seedUserId}`);

  // Check existing review count
  const existingCount = await db.select({ count: count() }).from(communityReviews);
  console.log(`✓ 기존 리뷰 수: ${existingCount[0].count}개`);

  const allReviews = [...lectureReviews, ...workbookReviews, ...academyReviews];
  let inserted = 0;
  let skipped = 0;

  for (const review of allReviews) {
    const createdAt = new Date(
      Date.now() - Math.floor(Math.random() * 90) * 24 * 60 * 60 * 1000
    );
    await db.insert(communityReviews).values({
      userId: seedUserId,
      type: review.type,
      targetName: review.targetName,
      instructor: "instructor" in review ? review.instructor ?? null : null,
      platform: "platform" in review ? (review as any).platform ?? null : null,
      publisher: "publisher" in review ? (review as any).publisher ?? null : null,
      subject: review.subject,
      region: "region" in review ? (review as any).region ?? null : null,
      district: "district" in review ? (review as any).district ?? null : null,
      overallRating: review.overallRating,
      ratingContent: review.ratingContent,
      ratingValue: review.ratingValue,
      ratingManage: review.ratingManage,
      title: review.title,
      content: review.content,
      prosTagIds: review.prosTagIds as string[],
      consTagIds: review.consTagIds as string[],
      gradeLevel: review.gradeLevel ?? null,
      gradeBefore: "gradeBefore" in review ? review.gradeBefore ?? null : null,
      gradeAfter: "gradeAfter" in review ? review.gradeAfter ?? null : null,
      studyDuration: review.studyDuration ?? null,
      likes: review.likes,
      views: review.views,
      isApproved: 1,
      createdAt,
    });
    inserted++;
  }

  console.log(`\n✅ 완료!`);
  console.log(`   - 인강 리뷰: ${lectureReviews.length}개`);
  console.log(`   - 문제집 리뷰: ${workbookReviews.length}개`);
  console.log(`   - 학원 리뷰: ${academyReviews.length}개`);
  console.log(`   - 총 ${inserted}개 삽입됨`);
  process.exit(0);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
